services:
  envio-boletas:
    build: .
    container_name: envio-boletas-api
    restart: unless-stopped
    ports:
      - "${PORT:-3500}:3500"
    dns:
      - 172.16.100.155
    extra_hosts:
      - "SRVBDP006:172.16.100.36"
      - "srvbdp006:172.16.100.36"
      - "SRVBDP006.byb.gt:172.16.100.36"
      - "srvbdp006.byb.gt:172.16.100.36"
    env_file: .env
    environment:
      NODE_ENV: production
      PORT: 3500
    volumes:
      - ./config:/app/config
      - boleta-temp:/app/Temp

volumes:
  boleta-temp:
